# Generated by Django 4.0.1 on 2022-01-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.TimeField(auto_now_add=True)),
                ('modified', models.TimeField(auto_now=True)),
                ('author', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.TimeField(auto_now_add=True)),
                ('modified', models.TimeField(auto_now=True)),
                ('author', models.CharField(max_length=32)),
                ('body', models.TextField(max_length=256)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.node')),
            ],
            options={
                'verbose_name_plural': 'replies',
            },
        ),
    ]
